### ISSUE TITLE
Browser won't close after authentication

### ISSUE THREAD

**Issue by DamienDoumer** [leifermendez/twitch-login-sdk#3]
First, thanks for making this plugin. 
I tried to use it, and noticed the browser won't close on authentication. I saw you mentioned: 
"Remember that the host origin (domain) must be the same as the redirect url. Otherwise the pop-up window will not close"

but what exactly do you mean by that ?
I'm testing on localhost, and used ngrok to tunnel to "https://localhost:4200" my redirect url in the config is :  https://5ebeb0387aaf.ngrok.io/
And what I registered in the twitch developer console is the same as the ngrok url above. 
But the browser still won;t close. in the console, I get this error: 

`DOMException: Blocked a frame with origin "https://localhost:4200" from accessing a cross-origin frame.
    at https://localhost:4200/main.js:916:69`

**Comment by leifermendez** [comment]
Hi Damien, well, 
__First:__ Make sure in your "Twitch Console Developer" the app settings included in "OAuth Redirect URLs" the url after login redirect.

![image](https://user-images.githubusercontent.com/15802366/88706130-b97ed380-d110-11ea-9370-cfef54f83aba.png)

__Second:__ If you trigger Login from "https://localhost:4200" your must redirect to any url belongs "https://localhost:4200", otherwise it won't work.

> Example: Trigger from "https://localhost:4200/oauth/login" redirect to "https://localhost:4200/callback"

Please comment!

**Comment by DamienDoumer** [comment]
ok, thanks
